DRAFT_PROMPT_VERSION = "draft-v7"
ROUTING_PROMPT_VERSION = "routing-v7"
REFINEMENT_PROMPT_VERSION = "refinement-v6"
SNOOZE_PROMPT_VERSION = "snooze-v2"

PROMPT_VERSIONS = {
    "draft": DRAFT_PROMPT_VERSION,
    "routing": ROUTING_PROMPT_VERSION,
    "refinement": REFINEMENT_PROMPT_VERSION,
    "snooze": SNOOZE_PROMPT_VERSION,
}
