DRAFT_PROMPT_VERSION = "draft-v5"
ROUTING_PROMPT_VERSION = "routing-v5"
REFINEMENT_PROMPT_VERSION = "refinement-v5"
SNOOZE_PROMPT_VERSION = "snooze-v2"
MEETING_REVIEW_PROMPT_VERSION = "meeting-review-v4"

PROMPT_VERSIONS = {
    "draft": DRAFT_PROMPT_VERSION,
    "routing": ROUTING_PROMPT_VERSION,
    "refinement": REFINEMENT_PROMPT_VERSION,
    "snooze": SNOOZE_PROMPT_VERSION,
    "meeting_review": MEETING_REVIEW_PROMPT_VERSION,
}
